--- 
test: 
  override: 
    - 
      ? "emulator -avd circleci-android22 -no-audio -no-window"
      : 
        background: true
        parallel: true
    - "circle-android wait-for-boot"
    - "sleep 30"
    - "adb shell input keyevent 82"
    - "./gradlew connectedAndroidTest -PdisablePreDex"
    - "cp -r app/build/outputs $CIRCLE_ARTIFACTS"
    - "cp -r app/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS"
