version: 2



jobs:

  build:

    docker:

      # specific environment version to avoid incompatible updates

      - image: bitriseio/docker-android:v2018_09_29-05_14-b1278



    working_directory: ~/MobileAppAutomationTest/AndroidDemo/



    steps:

      - run:

          name: Lists installed targets

          command: android list target

          environment:

            TERM: dumb



      - run:

          name: List available targets and other sdk modules

          command: sdkmanager --list --include_obsolete --verbose

          environment:

            TERM: dumb
      
      - checkout   
      
      - run:
          name: accept licenses
          command: cp -r ~/MobileAppAutomationTest/AndroidDemo/licenses/. $ANDROID_HOME/licenses/
          environment:
            TERM: dumb
      - run:
          name: Android dependences
          command: ./gradlew androidDependencies
          environment:
            TERM: dumb
            
  
      - run:
          name: path ANDROID_SDK_ROOT
          command: export ANDROID_SDK_ROOT=$ANDROID_HOME
          environment:
            TERM: dumb

      - run:

          name: Create avd

          command: echo no | avdmanager create avd -n testEmulator -k "system-images;android-25;google_apis;armeabi-v7a"

       #   command: echo no | avdmanager create avd -n testEmulator -k "system-images;android-25;google_apis;default;armeabi-v7a"

          environment:

            TERM: dumb



      - run:

          name: Start emulator

          command: /opt/android-sdk-linux/emulator/emulator -avd testEmulator -no-audio -no-window

          background: true

          environment:

            TERM: dumb



     



      - run:
            name: Wait emulator
            command: sleep 120
            environment:
              TERM: dumb
     
     
 
      - run:

          name: Expresso testing

          command: ./gradlew connectedAndroidTest

          environment:

            TERM: dumb
      - store_artifacts:

          path: app/build/reports
          
          destination: reports
      
      - store_test_results:

          path: app/build/outputs
