version: 2



jobs:

  build:

    docker:

      # specific environment version to avoid incompatible updates

      - image: bitriseio/docker-android:v2017_09_09-06_45-b744



    working_directory: ~/MobileAppAutomationTest/AndroidDemo/



    steps:



      - run:

          name: Lists installed targets

          command: android list target

          environment:

            TERM: dumb



      - run:

          name: List available targets and other sdk modules

          command: sdkmanager --list --include_obsolete --verbose

          environment:

            TERM: dumb
      - run:
          name: accept licenses
          command: cp -r licenses/ $ANDROID_HOME/licenses
          environment:
            TERM: dumb

      - run:

          name: Create avd

       #   command: echo no | avdmanager create avd -n testEmulator -k "system-images;android-23;google_apis;armeabi-v7a"

          command: echo no | avdmanager create avd -n testEmulator -k "system-images;android-24;default;armeabi-v7a"

          environment:

            TERM: dumb



      - run:

          name: Start emulator

          command: /opt/android-sdk-linux/emulator/emulator -avd testEmulator -no-audio -no-window

          background: true

          environment:

            TERM: dumb



      - checkout



      - run:
            name: Wait emulator
            command: ./android-wait-for-boot.sh
            environment:
              TERM: dumb

      - run:

          name: Remove lock screen

          command: adb shell input keyevent 82

          environment:

            TERM: dumb
 
      - run:

          name: Expresso testing

          command: ./gradlew connectedAndroidTest

          environment:

            TERM: dumb
      - store_artifacts:

          path: app/build/reports
          
          destination: reports
      
      - store_test_results:

          path: app/build/outputs
