--- 
dependencies: 
  cache_directories: 
    - /usr/local/android-sdk-linux/build-tools/25.0.2
    - /usr/local/android-sdk-linux/platforms/android-25
    - /usr/local/android-sdk-linux/extras/android/m2repository
  pre: 
    - "if [ ! -e /usr/local/android-sdk-linux/build-tools/25.0.2 ]; then echo y | android update sdk --all --no-ui --filter \"build-tools-25.0.2\"; fi;"
    - "if [ ! -e /usr/local/android-sdk-linux/platforms/android-25 ]; then echo y | android update sdk --all --no-ui --filter \"android-25\"; fi;"
    - "if ! $(grep -q \"Revision=44.0.0\" /usr/local/android-sdk-linux/extras/android/m2repository/source.properties); then echo y | android update sdk --all --no-ui --filter \"extra-android-m2repository\"; fi;"
deployment: 
  espresso: 
    branch: master
    commands: 
      - 
        ? "emulator -avd circleci-android22 -no-audio -no-window"
        : 
          background: true
          parallel: true
      - "circle-android wait-for-boot"
      - "sleep 30"
      - "adb shell input keyevent 82"
      - "./gradlew connectedAndroidTest -PdisablePreDex"
      - "cp -r app/build/outputs $CIRCLE_ARTIFACTS"
      - "cp -r app/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS"
general: 
  artifacts: 
    - app/build/reports/androidTests/connected
machine: 
  environment: 
    ADB_INSTALL_TIMEOUT: "10"
    GRADLE_OPTS: "-Dorg.gradle.jvmargs=\"-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError\""
    TERM: dumb
    TEST_FLAGS: "--configure-on-demand -PdisablePreDex"
  java: 
    version: oraclejdk8
  python: 
    version: "2.7.10"
test: 
  override: 
    - "./gradlew assembleDebug -PdisablePreDex"
